# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: FINE Open Source
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wearefine.github.io" # the base hostname & protocol for your site
twitter_username: wearefine

# Build settings
markdown: kramdown
projects:
  - title: Fae
    slug: fae
    logo: 'false'
  - title: Fryr
    slug: fryr
  - title: Fine Forever
    slug: fine-forever
  - title: Frob Core
    slug: frob-core
  - title: Maximus
    slug: maximus
  - title: Slim Gym
    slug: slim-gym
    logo: 'false'
